spring:
  messages:
    basename: messages/messages
  datasource:
    url: jdbc:postgresql://db-postgresql.cg6mtzrdu9a8.ap-south-1.rds.amazonaws.com:5432/newagenxt_dev?currentSchema=tenant_default
    username: postgres_user
    password: Newage@2022
    schemaname: tenant_default
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      profiles:
        active: dev


server:
  servlet:
    context-path: /nxt-wms
  port: 9093

